spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    name: ${POSTGRES_DB}

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
