spring:
  datasource:
    url: postgres://koyeb-adm:pJFkECuD6j5V@ep-broad-cell-a2j3sdae.eu-central-1.pg.koyeb.app/koyebdb
    username: koyeb-adm
    password: pJFkECuD6j5V
    name: koyebdb

  sql:
    init:
      mode: always # you won't do this in prod, I'm just doing this for demo purposes
